server:
  port: 8083

spring:
  application:
    name: pubaoyou-website
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql8配置驱动
    url: jdbc:mysql://172.16.149.12:3306/new_itssc?useUnicode=true&characterEncoding=utf-8
    username: root
    password: abc123
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000

mybatis:
  type-aliases-package: com.pubaoyou.dao.models
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
