server:
  port: 8082
spring:
  application:
    name: pubaoyou-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: service-hi
#          uri: lb://PUBAOYOU-SERVICE
#          predicates:
#          - Path=/service/**
#          filters:
#            - SwaggerHeaderFilter
#            - StripPrefix=1 #截取请求参数，如/hello/world/xxx,则截取后为/word/xxxx
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15  # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    registry-fetch-interval-seconds: 10 # 拉取服务注册信息间隔（缺省为30s）
    service-url:
      defaultZone: http://localhost:8080/eureka/
    healthcheck:
      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）
logging:
  config: classpath:logback-spring.xml