server:
  port: 8090

spring:
  application:
    name: pubaoyou-rabbitmq
  rabbitmq:
    # 集群地址，用逗号分隔
    connection-timeout: 15000
    username: admin
    password: itssc@123456
    virtual-host: /
    port: 30734
    host: 172.16.149.14






